import React, { useMemo, useState } from 'react';
import { BookOpen, Check, ChevronDown, ExternalLink, Lightbulb, Map, Search, Target, Users, WandSparkles, ArrowLeft } from 'lucide-react';
import { SectionGuide } from '../components/SectionGuide';

const PHASES = [
  { n:'۰۱', label:'پیش‌نیازها', title:'قبل از ژست، آدم و صحنه را بخوان', color:'var(--color-teal)', lessons:[['هدف عکس را مشخص کن','قبل از حرکت تصمیم بگیر عکس باید چه حسی داشته باشد: صمیمیت، قدرت، آرامش، شادی یا شکوه. ژست باید در خدمت حس باشد، نه برعکس.','سه کلمه بنویس: حس، داستان، نقطه تمرکز.'],['نور و پس‌زمینه را بررسی کن','جهت نور، خطوط معماری، فضای حرکت و رنگ لباس، انتخاب ژست را تعیین می‌کنند. ژست باز برای فضای باز است و ژست نزدیک برای نور نرم و کنترل‌شده.','قبل از صدا زدن سوژه، یک قاب خالی از لوکیشن پیدا کن.'],['با سوژه ارتباط بساز','اول یک حرکت ساده و بی‌خطر بده تا بدن از حالت انجماد بیرون بیاید. لبخند واقعی از گفت‌وگوی واقعی می‌آید، نه از دستور «لبخند بزن».','یک جمله شخصی و یک حرکت ساده برای شروع آماده کن.']] },
  { n:'۰۲', label:'اصول پایه', title:'بدن را از پا تا چشم بساز', color:'var(--color-gold)', lessons:[['پاها و وزن بدن','وزن را روی یک پا بینداز، پای دیگر سبک باشد. دو پا کاملاً موازی بدن را تخت و بی‌حرکت نشان می‌دهد.','یک ژست را با سه جای پای متفاوت امتحان کن.'],['لگن، شانه و خط بدن','بدن را صاف و خشک نکن. لگن و شانه کمی خلاف جهت هم باشند تا خط S یا مثلث بسازند.','فقط زاویه شانه را عوض کن و تفاوت را ببین.'],['دست‌ها و انگشت‌ها','دست معلق اضطراب می‌سازد. دست را به لباس، دسته‌گل، یقه، دست نفر مقابل یا محیط وصل کن. انگشت‌ها نرم و جدا باشند.','برای هر ژست سه نقطه تماس تعریف کن.'],['چانه، گردن و نگاه','چانه کمی جلو و پایین، گردن کشیده، نگاه با هدف. صورت آخرین قطعه پازل است.','اول نگاه را به نقطه مشخص بده، بعد شاتر بزن.']] },
  { n:'۰۳', label:'ساخت تنوع', title:'از یک ژست، ده ایده بساز', color:'var(--color-plum)', lessons:[['ژست پایه را نگه دار','لازم نیست ژست را از صفر عوض کنی. فقط یک متغیر را تغییر بده: نگاه، دست، زاویه، فاصله، ارتفاع دوربین یا حرکت.','فرمول: پایه + نگاه + دست + زاویه + فاصله + حرکت.'],['تعامل بساز','برای زوج‌ها تماس هدفمند تعریف کن: دست، شانه، پیشانی، کمر یا نگاه. فاصله زیاد سرد است، تماس بی‌منطق هم فرم را خراب می‌کند.','یک ژست را در سه فاصله اجرا کن: بدون تماس، تماس دست، تماس کامل.'],['حرکت کنترل‌شده بده','راه رفتن، چرخیدن، نفس کشیدن، مرتب کردن لباس یا گفتن یک راز، حالت واقعی می‌سازد.','از هر ژست ثابت، یک نسخه راه رفتن و یک نسخه واکنش طبیعی بساز.']] },
  { n:'۰۴', label:'کار حرفه‌ای', title:'ژست را با نور، دوربین و ایمنی کامل کن', color:'var(--color-rose)', lessons:[['زاویه دوربین را انتخاب کن','زاویه پایین شکوه می‌دهد، زاویه هم‌سطح صمیمیت می‌سازد، زاویه بالا لطافت و نظم را بیشتر می‌کند.','قبل از تغییر ژست، سه ارتفاع دوربین را تست کن.'],['کادر و فضای حرکت','در جهت حرکت فضای خالی بگذار. معماری قرینه، دوربین تراز می‌خواهد. لباس و دست‌ها را در لبه کادر قطع نکن.','یک بار قاب را برای حرکت و یک بار برای پرتره ببند.'],['ایمنی و راحتی','دیپ، بلند کردن، پله، آب و سطح لغزنده فقط با کنترل و رضایت اجرا شوند. نسخه کم‌ریسک هر ژست را بدان.','برای هر ژست حرکتی یک جایگزین ساده داشته باش.']] },
];
const SOURCES=[['Lindsay Adler، ساخت تنوع از ژست پایه','فرآیند ۱۰ مرحله‌ای برای اینکه با چند ژست پایه همیشه ایده داشته باشی.','https://www.oreilly.com/library/view/the-photographers-guide/9781492018797/Text/chapter10.xhtml'],['CreativeLive، Posing 101','شانه، چانه، چشم، دست، پا، زوج و گروه.','https://www.creativelive.com/classes/posing-101-lindsay-adler'],['Rangefinder، زبان بدن','چطور بدن و حالت، پیام احساسی عکس را منتقل می‌کند.','https://rangefinderonline.com/news-features/tips-techniques/the-art-of-posing-body-language-basics/'],['SLR Lounge، ژست طبیعی','حرکت‌های کوچک و کارگردانی واقعی به جای حالت مصنوعی.','https://www.slrlounge.com/simple-posing-guide-for-natural-authentic-portraits/']];
export const PrinciplesView: React.FC=()=>{ const [phase,setPhase]=useState(0); const [open,setOpen]=useState('0-0'); const [q,setQ]=useState(''); const current=PHASES[phase]; const lessons=current.lessons.filter(x=>`${x[0]} ${x[1]} ${x[2]}`.includes(q.trim())); return <div className="space-y-5">
  <SectionGuide section="principles" title="اصول ژست‌دهی چیست؟" text="اینجا یک مسیر مرحله‌ای داری: از خواندن صحنه و بدن شروع می‌کنی، بعد ژست پایه می‌سازی، تنوع می‌دهی و در پایان آن را با نور و دوربین حرفه‌ای می‌کنی." />
  <section className="relative pt-1"><div className="flex items-end justify-between gap-3"><div><span className="pill"><WandSparkles className="w-3 h-3 text-gold"/> مسیر یادگیری</span><h1 className="text-[24px] font-extrabold leading-tight mt-3">ژست حفظ نکن،<br/><span className="text-gold">ژست بساز.</span></h1></div><span className="text-[11px] text-muted">مرحله {phase+1} از {PHASES.length}</span></div>
    <div className="mt-6 relative"><div className="absolute top-5 right-5 left-5 h-px bg-line"/><div className="relative flex justify-between">{PHASES.map((p,i)=><button key={p.n} onClick={()=>{setPhase(i);setOpen(`${i}-0`)}} className="flex flex-col items-center gap-2" style={{color:i===phase?p.color:'var(--color-faint)'}}><span className="w-10 h-10 rounded-full flex items-center justify-center border-2 text-[11px] font-extrabold" style={{background:i<=phase?`color-mix(in srgb, ${p.color} 16%, var(--color-bg))`:'var(--color-bg)',borderColor:i<=phase?p.color:'var(--color-line)'}}>{i<phase?<Check className="w-4 h-4"/>:p.n}</span><span className="text-[10px] font-bold">{p.label}</span></button>)}</div></div>
  </section>
  <section className="card p-4" style={{borderColor:`color-mix(in srgb, ${current.color} 45%, var(--color-line))`}}><div className="flex items-start gap-3"><span className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0" style={{background:`color-mix(in srgb, ${current.color} 17%, transparent)`,color:current.color}}><Target className="w-5 h-5"/></span><div><span className="text-[10px] font-extrabold" style={{color:current.color}}>{current.label}</span><h2 className="text-[18px] font-extrabold mt-1">{current.title}</h2><p className="text-[11px] text-muted mt-1">بعد از این مرحله باید بتوانی آگاهانه تصمیم بگیری، نه اینکه فقط یک عکس را تقلید کنی.</p></div></div></section>
  <div className="card p-3"><div className="relative"><Search className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-faint"/><input value={q} onChange={e=>setQ(e.target.value)} className="field !pr-9" placeholder="جستجو در این مرحله..."/></div></div>
  <section className="relative mr-3 pr-5 border-r border-line space-y-3">{lessons.map((l,i)=>{const id=`${phase}-${i}`, is=open===id;return <div key={id} className="relative"><span className="absolute -right-[30px] top-4 w-3 h-3 rounded-full border-2" style={{background:'var(--color-bg)',borderColor:current.color}}/><div className="card overflow-hidden"><button onClick={()=>setOpen(is?'':id)} className="w-full text-right p-4 flex items-center gap-3"><span className="text-[11px] font-extrabold" style={{color:current.color}}>۰{i+1}</span><span className="flex-1 font-extrabold text-[13px]">{l[0]}</span><ChevronDown className="w-4 h-4 text-faint" style={{transform:is?'rotate(180deg)':'none'}}/></button>{is&&<div className="px-4 pb-4 space-y-3 a-fade"><p className="text-[12.5px] leading-7 text-muted">{l[1]}</p><div className="p-3 rounded-2xl" style={{background:`color-mix(in srgb, ${current.color} 10%, transparent)`}}><span className="text-[10px] font-extrabold" style={{color:current.color}}>تمرین سر صحنه</span><p className="text-[12px] leading-relaxed mt-1">{l[2]}</p></div></div>}</div></div>})}</section>
  <div className="flex items-center justify-between gap-2"><button disabled={phase===0} onClick={()=>{setPhase(phase-1);setOpen(`${phase-1}-0`)}} className="btn btn-ghost disabled:opacity-40"><ArrowLeft className="w-4 h-4 rotate-180"/> مرحله قبل</button><button disabled={phase===PHASES.length-1} onClick={()=>{setPhase(phase+1);setOpen(`${phase+1}-0`)}} className="btn btn-primary disabled:opacity-40">مرحله بعد <ArrowLeft className="w-4 h-4"/></button></div>
  <section className="pt-3"><h2 className="font-extrabold text-[15px] flex items-center gap-2"><BookOpen className="w-4 h-4 text-gold"/> منابع منتخب</h2><p className="text-[11px] text-muted mt-1">مطالب داخل برنامه خلاصه و بازنویسی شده‌اند، منابع برای مطالعه عمیق‌ترند.</p><div className="space-y-2 mt-3">{SOURCES.map(s=><a key={s[0]} href={s[2]} target="_blank" rel="noreferrer" className="flex items-center gap-3 p-3 rounded-2xl border border-line"><span className="flex-1"><b className="block text-[12px]">{s[0]}</b><small className="block text-[10px] text-muted mt-1">{s[1]}</small></span><ExternalLink className="w-3.5 h-3.5 text-gold"/></a>)}</div></section>
 </div>}
